Also need to check for java.lang.NoClassDefFoundError to see if Mail or jaf is persent PR: Obtained from: Submitted by: Reviewed by:
git-svn-id: https://svn.apache.org/repos/asf/webservices/axis1/trunk@252756 13f79535-47bb-0310-9956-ffa450edef68